### ISSUE TITLE
Use EFF's wordlist

### ISSUE THREAD

**Issue by roryk** [roryk/quantum-diceware#3]
https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases has better wordlists, in particular https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt is nice.

**Comment by roryk** [comment]
https://github.com/roryk/quantum-diceware/blob/master/scripts/quantum-diceware.py#L45 is where we pull in the list and it looks like the list is in the right format so we can just drop it in as `eff.asc` and swap there that is pointing to use that list.

**Comment by grahams** [comment]
@roryk there's already a 'wordfile' command-line argument already, so we could probably just add any/all of the EFF lists and either change the default or not

**Comment by grahams** [comment]
working on this over at http://github.com/grahams/quantum-diceware/tree/eff-wordlists

**Comment by grahams** [comment]
Pull request #4 covers it i think

**Comment by roryk** [comment]
THX, rofl just noticed this was open.
